"""crear_todas_las_tablas_corregido

Revision ID: 24e95c15af39
Revises: 
Create Date: 2025-09-11 21:23:03.891070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24e95c15af39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id_region', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_region'),
    sa.UniqueConstraint('codigo'),
    schema='vecindapp'
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.CheckConstraint("codigo IN ('vecino','directiva','admin')", name='ck_rol_codigo'),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('codigo'),
    schema='vecindapp'
    )
    op.create_table('comuna',
    sa.Column('id_comuna', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_region', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['vecindapp.region.id_region'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_comuna'),
    sa.UniqueConstraint('id_region', 'nombre', name='ux_comuna'),
    schema='vecindapp'
    )
    op.create_table('junta',
    sa.Column('id_junta', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_comuna', sa.BigInteger(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['vecindapp.comuna.id_comuna'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_junta'),
    schema='vecindapp'
    )
    op.create_table('espacio',
    sa.Column('id_espacio', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo IN ('cancha','sala','plaza','otro')", name='ck_espacio_tipo'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_espacio'),
    schema='vecindapp'
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('pass_hash', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('id_junta', 'email', name='ux_usuario_email'),
    schema='vecindapp'
    )
    op.create_table('transaccion',
    sa.Column('id_transaccion', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('origen_tipo', sa.Text(), nullable=False),
    sa.Column('origen_id', sa.BigInteger(), nullable=False),
    sa.Column('proveedor', sa.Text(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('moneda', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('creado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('autorizado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anulado_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('iniciado','autorizado','rechazado','anulado')", name='ck_tx_estado'),
    sa.CheckConstraint("origen_tipo IN ('certificado_pedido','reserva')", name='ck_tx_origen_tipo'),
    sa.CheckConstraint("proveedor IN ('webpay','mercadopago','paypal')", name='ck_tx_proveedor'),
    sa.CheckConstraint('monto >= 0', name='ck_tx_monto'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_transaccion'),
    schema='vecindapp'
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('id_rol', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['vecindapp.rol.id_rol'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol'),
    schema='vecindapp'
    )
    op.create_table('vecino',
    sa.Column('id_vecino', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('nombres', sa.Text(), nullable=False),
    sa.Column('apellido_paterno', sa.Text(), nullable=False),
    sa.Column('apellido_materno', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('foto_perfil', sa.LargeBinary(), nullable=True),
    sa.Column('id_comuna', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['vecindapp.comuna.id_comuna'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_vecino'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('rut'),
    schema='vecindapp'
    )
    op.create_table('certificado_pedido',
    sa.Column('id_pedido', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_vecino', sa.BigInteger(), nullable=False),
    sa.Column('creado_por', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('iniciado','pagado','emitido','rechazado')", name='ck_cert_pedido_estado'),
    sa.ForeignKeyConstraint(['creado_por'], ['vecindapp.usuario.id_usuario'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vecino'], ['vecindapp.vecino.id_vecino'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pedido'),
    schema='vecindapp'
    )
    op.create_table('detalle_transaccion',
    sa.Column('id_detalle', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_transaccion', sa.BigInteger(), nullable=False),
    sa.Column('etiqueta', sa.Text(), nullable=True),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_transaccion'], ['vecindapp.transaccion.id_transaccion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle'),
    schema='vecindapp'
    )
    op.create_table('pago_externo',
    sa.Column('id_pago_externo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_transaccion', sa.BigInteger(), nullable=False),
    sa.Column('codigo_respuesta', sa.Text(), nullable=True),
    sa.Column('estado_pago', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_transaccion'], ['vecindapp.transaccion.id_transaccion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pago_externo'),
    sa.UniqueConstraint('id_transaccion', name='ux_pagoext_tx'),
    schema='vecindapp'
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_espacio', sa.BigInteger(), nullable=False),
    sa.Column('id_vecino', sa.BigInteger(), nullable=False),
    sa.Column('creado_por', sa.BigInteger(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente','pagada','aprobada','rechazada','cancelada','confirmada')", name='ck_reserva_estado'),
    sa.CheckConstraint('fin > inicio', name='ck_reserva_intervalo'),
    sa.ForeignKeyConstraint(['creado_por'], ['vecindapp.usuario.id_usuario'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_espacio'], ['vecindapp.espacio.id_espacio'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vecino'], ['vecindapp.vecino.id_vecino'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reserva'),
    schema='vecindapp'
    )
    op.create_table('certificado',
    sa.Column('id_certificado', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_pedido', sa.BigInteger(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('comuna', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['vecindapp.certificado_pedido.id_pedido'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_certificado'),
    sa.UniqueConstraint('id_junta', 'numero', name='ux_cert_num'),
    sa.UniqueConstraint('id_pedido'),
    schema='vecindapp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificado', schema='vecindapp')
    op.drop_table('reserva', schema='vecindapp')
    op.drop_table('pago_externo', schema='vecindapp')
    op.drop_table('detalle_transaccion', schema='vecindapp')
    op.drop_table('certificado_pedido', schema='vecindapp')
    op.drop_table('vecino', schema='vecindapp')
    op.drop_table('usuario_rol', schema='vecindapp')
    op.drop_table('transaccion', schema='vecindapp')
    op.drop_table('usuario', schema='vecindapp')
    op.drop_table('espacio', schema='vecindapp')
    op.drop_table('junta', schema='vecindapp')
    op.drop_table('comuna', schema='vecindapp')
    op.drop_table('rol', schema='vecindapp')
    op.drop_table('region', schema='vecindapp')
    # ### end Alembic commands ###
