"""mensaje

Revision ID: 5631a0285408
Revises: 049522c2bff2
Create Date: 2025-09-08 22:44:46.770778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5631a0285408'
down_revision: Union[str, Sequence[str], None] = '049522c2bff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaccion', schema='vecindApp')
    op.drop_table('certificado_pedido', schema='vecindApp')
    op.drop_table('reserva', schema='vecindApp')
    op.drop_table('comuna', schema='vecindApp')
    op.drop_table('usuario', schema='vecindApp')
    op.drop_table('pago_externo', schema='vecindApp')
    op.drop_table('rol', schema='vecindApp')
    op.drop_table('espacio', schema='vecindApp')
    op.drop_table('certificado', schema='vecindApp')
    op.drop_table('region', schema='vecindApp')
    op.drop_table('vecino', schema='vecindApp')
    op.drop_table('detalle_transaccion', schema='vecindApp')
    op.drop_table('usuario_rol', schema='vecindApp')
    op.drop_table('junta', schema='vecindApp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('junta',
    sa.Column('id_junta', sa.BIGINT(), server_default=sa.text('nextval(\'"vecindApp".junta_id_junta_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_comuna', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['vecindApp.comuna.id_comuna'], name='junta_id_comuna_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_junta', name='junta_pkey'),
    schema='vecindApp',
    postgresql_ignore_search_path=False
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_rol', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['vecindApp.rol.id_rol'], name=op.f('usuario_rol_id_rol_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindApp.usuario.id_usuario'], name=op.f('usuario_rol_id_usuario_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol', name=op.f('usuario_rol_pkey')),
    schema='vecindApp'
    )
    op.create_table('detalle_transaccion',
    sa.Column('id_detalle', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_transaccion', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('etiqueta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_transaccion'], ['vecindApp.transaccion.id_transaccion'], name=op.f('detalle_transaccion_id_transaccion_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle', name=op.f('detalle_transaccion_pkey')),
    schema='vecindApp'
    )
    op.create_table('vecino',
    sa.Column('id_vecino', sa.BIGINT(), server_default=sa.text('nextval(\'"vecindApp".vecino_id_vecino_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nombres', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_comuna', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['vecindApp.comuna.id_comuna'], name='vecino_id_comuna_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindApp.junta.id_junta'], name='vecino_id_junta_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindApp.usuario.id_usuario'], name='vecino_id_usuario_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_vecino', name='vecino_pkey'),
    sa.UniqueConstraint('id_usuario', name='vecino_id_usuario_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vecindApp',
    postgresql_ignore_search_path=False
    )
    op.create_table('region',
    sa.Column('id_region', sa.BIGINT(), server_default=sa.text('nextval(\'"vecindApp".region_id_region_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_region', name='region_pkey'),
    sa.UniqueConstraint('nombre', name='region_nombre_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vecindApp',
    postgresql_ignore_search_path=False
    )
    op.create_table('certificado',
    sa.Column('id_certificado', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_pedido', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha_emision', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comuna', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindApp.junta.id_junta'], name=op.f('certificado_id_junta_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['vecindApp.certificado_pedido.id_pedido'], name=op.f('certificado_id_pedido_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_certificado', name=op.f('certificado_pkey')),
    sa.UniqueConstraint('id_junta', 'numero', name=op.f('ux_cert_num'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('id_pedido', name=op.f('certificado_id_pedido_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vecindApp'
    )
    op.create_table('espacio',
    sa.Column('id_espacio', sa.BIGINT(), server_default=sa.text('nextval(\'"vecindApp".espacio_id_espacio_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('capacidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint("tipo = ANY (ARRAY['cancha'::text, 'sala'::text, 'plaza'::text, 'otro'::text])", name='ck_espacio_tipo'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindApp.junta.id_junta'], name='espacio_id_junta_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_espacio', name='espacio_pkey'),
    schema='vecindApp',
    postgresql_ignore_search_path=False
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("codigo = ANY (ARRAY['vecino'::text, 'directiva'::text, 'admin'::text])", name=op.f('ck_rol_codigo')),
    sa.PrimaryKeyConstraint('id_rol', name=op.f('rol_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('rol_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vecindApp'
    )
    op.create_table('pago_externo',
    sa.Column('id_pago_externo', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_transaccion', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('codigo_respuesta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado_pago', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fecha_respuesta', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_transaccion'], ['vecindApp.transaccion.id_transaccion'], name=op.f('pago_externo_id_transaccion_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pago_externo', name=op.f('pago_externo_pkey')),
    sa.UniqueConstraint('id_transaccion', name=op.f('ux_pagoext_tx'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vecindApp'
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.BIGINT(), server_default=sa.text('nextval(\'"vecindApp".usuario_id_usuario_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pass_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ultimo_acceso', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindApp.junta.id_junta'], name='usuario_id_junta_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', name='usuario_pkey'),
    sa.UniqueConstraint('id_junta', 'email', name='ux_usuario_email', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vecindApp',
    postgresql_ignore_search_path=False
    )
    op.create_table('comuna',
    sa.Column('id_comuna', sa.BIGINT(), server_default=sa.text('nextval(\'"vecindApp".comuna_id_comuna_seq\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_region', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['vecindApp.region.id_region'], name='comuna_id_region_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_comuna', name='comuna_pkey'),
    sa.UniqueConstraint('id_region', 'nombre', name='ux_comuna', postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vecindApp',
    postgresql_ignore_search_path=False
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_espacio', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_vecino', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('creado_por', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('inicio', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('fin', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado = ANY (ARRAY['pendiente'::text, 'pagada'::text, 'aprobada'::text, 'rechazada'::text, 'cancelada'::text, 'confirmada'::text])", name=op.f('ck_reserva_estado')),
    sa.CheckConstraint('fin > inicio', name=op.f('ck_reserva_intervalo')),
    sa.ForeignKeyConstraint(['creado_por'], ['vecindApp.usuario.id_usuario'], name=op.f('reserva_creado_por_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_espacio'], ['vecindApp.espacio.id_espacio'], name=op.f('reserva_id_espacio_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindApp.junta.id_junta'], name=op.f('reserva_id_junta_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vecino'], ['vecindApp.vecino.id_vecino'], name=op.f('reserva_id_vecino_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reserva', name=op.f('reserva_pkey')),
    schema='vecindApp'
    )
    op.create_table('certificado_pedido',
    sa.Column('id_pedido', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_vecino', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('creado_por', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("estado = ANY (ARRAY['iniciado'::text, 'pagado'::text, 'emitido'::text, 'rechazado'::text])", name=op.f('ck_cert_pedido_estado')),
    sa.ForeignKeyConstraint(['creado_por'], ['vecindApp.usuario.id_usuario'], name=op.f('certificado_pedido_creado_por_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindApp.junta.id_junta'], name=op.f('certificado_pedido_id_junta_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vecino'], ['vecindApp.vecino.id_vecino'], name=op.f('certificado_pedido_id_vecino_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pedido', name=op.f('certificado_pedido_pkey')),
    schema='vecindApp'
    )
    op.create_table('transaccion',
    sa.Column('id_transaccion', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('origen_tipo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('origen_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('proveedor', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('moneda', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('autorizado_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('anulado_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("estado = ANY (ARRAY['iniciado'::text, 'autorizado'::text, 'rechazado'::text, 'anulado'::text])", name=op.f('ck_tx_estado')),
    sa.CheckConstraint("origen_tipo = ANY (ARRAY['certificado_pedido'::text, 'reserva'::text])", name=op.f('ck_tx_origen_tipo')),
    sa.CheckConstraint("proveedor = ANY (ARRAY['webpay'::text, 'mercadopago'::text, 'paypal'::text])", name=op.f('ck_tx_proveedor')),
    sa.CheckConstraint('monto >= 0::numeric', name=op.f('ck_tx_monto')),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindApp.junta.id_junta'], name=op.f('transaccion_id_junta_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindApp.usuario.id_usuario'], name=op.f('transaccion_id_usuario_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_transaccion', name=op.f('transaccion_pkey')),
    schema='vecindApp'
    )
    # ### end Alembic commands ###
