"""implementar_tablas_maestras

Revision ID: d08f032c9633
Revises: 3b2e1947553a
Create Date: 2025-10-06 19:38:55.990518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08f032c9633'
down_revision: Union[str, Sequence[str], None] = '3b2e1947553a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_certificado',
    sa.Column('id_estado', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre_estado', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('nombre_estado'),
    schema='vecindapp'
    )
    op.create_table('estado_reserva',
    sa.Column('id_estado', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre_estado', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('nombre_estado'),
    schema='vecindapp'
    )
    op.create_table('motivo_solicitud',
    sa.Column('id_motivo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('grupo', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_motivo'),
    sa.UniqueConstraint('motivo'),
    schema='vecindapp'
    )
    op.create_table('tipo_espacio',
    sa.Column('id_tipo', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo'),
    sa.UniqueConstraint('tipo'),
    schema='vecindapp'
    )
    
    # Poblar tablas maestras con datos iniciales
    # Estados de certificado
    op.execute("""
        INSERT INTO vecindapp.estado_certificado (nombre_estado, descripcion, activo) VALUES
        ('pendiente_pago', 'Certificado pendiente de pago', true),
        ('generado', 'Certificado generado y listo', true),
        ('entregado', 'Certificado entregado al solicitante', true)
    """)
    
    # Estados de reserva
    op.execute("""
        INSERT INTO vecindapp.estado_reserva (nombre_estado, descripcion, activo) VALUES
        ('pendiente', 'Reserva pendiente de confirmación', true),
        ('pagada', 'Reserva pagada', true),
        ('aprobada', 'Reserva aprobada por la junta', true),
        ('rechazada', 'Reserva rechazada', true),
        ('cancelada', 'Reserva cancelada', true),
        ('confirmada', 'Reserva confirmada y activa', true)
    """)
    
    # Tipos de espacio
    op.execute("""
        INSERT INTO vecindapp.tipo_espacio (tipo, descripcion, activo) VALUES
        ('cancha', 'Cancha deportiva', true),
        ('sala', 'Sala de reuniones o eventos', true),
        ('plaza', 'Plaza o espacio al aire libre', true),
        ('otro', 'Otro tipo de espacio', true)
    """)
    
    # Motivos de solicitud (extraídos del frontend)
    op.execute("""
        INSERT INTO vecindapp.motivo_solicitud (motivo, grupo, descripcion, activo) VALUES
        ('Postulación a beneficios sociales (Registro Social de Hogares, subsidios habitacionales, bonos)', 'Trámites ante instituciones públicas', 'Para postular a beneficios sociales del estado', true),
        ('Procesos en municipalidades (inscripción en juntas de vecinos, becas municipales o ayudas sociales)', 'Trámites ante instituciones públicas', 'Para trámites municipales', true),
        ('Solicitudes en el SII o Tesorería para acreditar domicilio tributario', 'Trámites ante instituciones públicas', 'Para acreditar domicilio tributario', true),
        ('Juicios civiles, laborales o de familia (para demostrar residencia)', 'Procesos judiciales o notariales', 'Para procesos judiciales', true),
        ('Trámites de posesión efectiva, herencias o escrituras', 'Procesos judiciales o notariales', 'Para trámites notariales', true),
        ('Cambio de domicilio en causas judiciales', 'Procesos judiciales o notariales', 'Para cambio de domicilio judicial', true),
        ('Acreditar residencia ante el Servicio Nacional de Migraciones', 'Trámites migratorios', 'Para trámites migratorios', true),
        ('Solicitudes de permanencia definitiva, visados o nacionalización', 'Trámites migratorios', 'Para permanencia definitiva', true),
        ('Bancos o financieras (abrir cuentas, solicitar créditos)', 'Instituciones privadas', 'Para trámites bancarios', true),
        ('Aseguradoras o instituciones educativas para validar dirección', 'Instituciones privadas', 'Para validar dirección', true),
        ('Postulación a colegios con criterios de cercanía', 'Otros casos prácticos', 'Para postulación escolar', true),
        ('Contratos de arriendo o servicios básicos sin boletas propias', 'Otros casos prácticos', 'Para contratos de servicios', true)
    """)
    # Agregar nuevas columnas como nullable primero
    op.add_column('certificado_pedido', sa.Column('id_estado', sa.BigInteger(), nullable=True), schema='vecindapp')
    op.add_column('certificado_pedido', sa.Column('id_motivo', sa.BigInteger(), nullable=True), schema='vecindapp')
    
    # Migrar datos existentes
    # Para certificados: mapear estados existentes a nuevos IDs
    op.execute("""
        UPDATE vecindapp.certificado_pedido 
        SET id_estado = (
            CASE 
                WHEN estado = 'iniciado' THEN 1  -- pendiente_pago
                WHEN estado = 'pendiente_pago' THEN 1  -- pendiente_pago
                WHEN estado = 'emitido' THEN 2  -- generado
                WHEN estado = 'rechazado' THEN 1  -- pendiente_pago (por defecto)
                ELSE 1  -- pendiente_pago por defecto
            END
        )
    """)
    
    # Para motivos: crear un motivo genérico para datos existentes
    op.execute("""
        INSERT INTO vecindapp.motivo_solicitud (motivo, grupo, descripcion, activo) 
        VALUES ('Motivo no especificado', 'Otros casos prácticos', 'Motivo de solicitud previo a la implementación de catálogo', true)
        ON CONFLICT (motivo) DO NOTHING
    """)
    
    op.execute("""
        UPDATE vecindapp.certificado_pedido 
        SET id_motivo = (SELECT id_motivo FROM vecindapp.motivo_solicitud WHERE motivo = 'Motivo no especificado')
        WHERE motivo_solicitud IS NOT NULL
    """)
    
    # Hacer las columnas NOT NULL después de migrar
    op.alter_column('certificado_pedido', 'id_estado', nullable=False, schema='vecindapp')
    op.alter_column('certificado_pedido', 'id_motivo', nullable=False, schema='vecindapp')
    op.alter_column('certificado_pedido', 'valor_certificado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False,
               schema='vecindapp')
    op.drop_index(op.f('ix_cert_pedido_estado'), table_name='certificado_pedido', schema='vecindapp')
    op.create_index('ix_cert_pedido_estado', 'certificado_pedido', ['id_junta', 'id_estado'], unique=False, schema='vecindapp')
    op.create_foreign_key(None, 'certificado_pedido', 'estado_certificado', ['id_estado'], ['id_estado'], source_schema='vecindapp', referent_schema='vecindapp', ondelete='RESTRICT')
    op.create_foreign_key(None, 'certificado_pedido', 'motivo_solicitud', ['id_motivo'], ['id_motivo'], source_schema='vecindapp', referent_schema='vecindapp', ondelete='RESTRICT')
    op.drop_column('certificado_pedido', 'estado', schema='vecindapp')
    op.drop_column('certificado_pedido', 'motivo_solicitud', schema='vecindapp')
    # Agregar nueva columna como nullable primero
    op.add_column('espacio', sa.Column('id_tipo', sa.BigInteger(), nullable=True), schema='vecindapp')
    
    # Migrar tipos de espacio existentes
    op.execute("""
        UPDATE vecindapp.espacio 
        SET id_tipo = (
            CASE 
                WHEN tipo = 'cancha' THEN 1
                WHEN tipo = 'sala' THEN 2
                WHEN tipo = 'plaza' THEN 3
                WHEN tipo = 'otro' THEN 4
                ELSE 4  -- otro por defecto
            END
        )
    """)
    
    # Hacer la columna NOT NULL después de migrar
    op.alter_column('espacio', 'id_tipo', nullable=False, schema='vecindapp')
    op.create_foreign_key(None, 'espacio', 'tipo_espacio', ['id_tipo'], ['id_tipo'], source_schema='vecindapp', referent_schema='vecindapp', ondelete='RESTRICT')
    op.drop_column('espacio', 'tipo', schema='vecindapp')
    # Agregar nueva columna como nullable primero
    op.add_column('reserva', sa.Column('id_estado', sa.BigInteger(), nullable=True), schema='vecindapp')
    
    # Migrar estados de reserva existentes
    op.execute("""
        UPDATE vecindapp.reserva 
        SET id_estado = (
            CASE 
                WHEN estado = 'pendiente' THEN 1
                WHEN estado = 'pagada' THEN 2
                WHEN estado = 'aprobada' THEN 3
                WHEN estado = 'rechazada' THEN 4
                WHEN estado = 'cancelada' THEN 5
                WHEN estado = 'confirmada' THEN 6
                ELSE 1  -- pendiente por defecto
            END
        )
    """)
    
    # Hacer la columna NOT NULL después de migrar
    op.alter_column('reserva', 'id_estado', nullable=False, schema='vecindapp')
    op.alter_column('reserva', 'valor_reserva',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False,
               schema='vecindapp')
    op.drop_index(op.f('ix_reserva_estado'), table_name='reserva', schema='vecindapp')
    op.create_index('ix_reserva_estado', 'reserva', ['id_junta', 'id_estado'], unique=False, schema='vecindapp')
    op.create_foreign_key(None, 'reserva', 'estado_reserva', ['id_estado'], ['id_estado'], source_schema='vecindapp', referent_schema='vecindapp', ondelete='RESTRICT')
    op.drop_column('reserva', 'estado', schema='vecindapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=False), schema='vecindapp')
    op.drop_constraint(None, 'reserva', schema='vecindapp', type_='foreignkey')
    op.drop_index('ix_reserva_estado', table_name='reserva', schema='vecindapp')
    op.create_index(op.f('ix_reserva_estado'), 'reserva', ['id_junta', 'estado'], unique=False, schema='vecindapp')
    op.alter_column('reserva', 'valor_reserva',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0.00'),
               existing_nullable=False,
               schema='vecindapp')
    op.drop_column('reserva', 'id_estado', schema='vecindapp')
    op.add_column('espacio', sa.Column('tipo', sa.TEXT(), autoincrement=False, nullable=False), schema='vecindapp')
    op.drop_constraint(None, 'espacio', schema='vecindapp', type_='foreignkey')
    op.drop_column('espacio', 'id_tipo', schema='vecindapp')
    op.add_column('certificado_pedido', sa.Column('motivo_solicitud', sa.TEXT(), autoincrement=False, nullable=True), schema='vecindapp')
    op.add_column('certificado_pedido', sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=False), schema='vecindapp')
    op.drop_constraint(None, 'certificado_pedido', schema='vecindapp', type_='foreignkey')
    op.drop_constraint(None, 'certificado_pedido', schema='vecindapp', type_='foreignkey')
    op.drop_index('ix_cert_pedido_estado', table_name='certificado_pedido', schema='vecindapp')
    op.create_index(op.f('ix_cert_pedido_estado'), 'certificado_pedido', ['id_junta', 'estado'], unique=False, schema='vecindapp')
    op.alter_column('certificado_pedido', 'valor_certificado',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('2000.00'),
               existing_nullable=False,
               schema='vecindapp')
    op.drop_column('certificado_pedido', 'id_motivo', schema='vecindapp')
    op.drop_column('certificado_pedido', 'id_estado', schema='vecindapp')
    op.drop_table('tipo_espacio', schema='vecindapp')
    op.drop_table('motivo_solicitud', schema='vecindapp')
    op.drop_table('estado_reserva', schema='vecindapp')
    op.drop_table('estado_certificado', schema='vecindapp')
    # ### end Alembic commands ###
