"""migracion_inicial_completa

Revision ID: 371433ac8f3c
Revises: 
Create Date: 2025-10-01 22:26:29.773922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371433ac8f3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id_region', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_region'),
    sa.UniqueConstraint('codigo'),
    schema='vecindapp'
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.CheckConstraint("codigo IN ('vecino','directiva','admin')", name='ck_rol_codigo'),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('codigo'),
    schema='vecindapp'
    )
    op.create_table('webhook_event',
    sa.Column('id_webhook_event', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('processing_attempts', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id_payment_transaction', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("provider = ANY (ARRAY['mercadopago'::text, 'stripe'::text, 'webpay'::text])", name='ck_webhook_event_provider'),
    sa.CheckConstraint("status = ANY (ARRAY['received'::text, 'processing'::text, 'processed'::text, 'failed'::text, 'ignored'::text])", name='ck_webhook_event_status'),
    sa.PrimaryKeyConstraint('id_webhook_event'),
    schema='vecindapp'
    )
    op.create_index('ix_webhook_provider_external_id', 'webhook_event', ['provider', 'external_id'], unique=True, schema='vecindapp')
    op.create_table('comuna',
    sa.Column('id_comuna', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_region', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['vecindapp.region.id_region'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_comuna'),
    sa.UniqueConstraint('id_region', 'nombre', name='ux_comuna'),
    schema='vecindapp'
    )
    op.create_table('junta',
    sa.Column('id_junta', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_comuna', sa.BigInteger(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_constitucion', sa.Date(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['vecindapp.comuna.id_comuna'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_junta'),
    sa.UniqueConstraint('rut'),
    schema='vecindapp'
    )
    op.create_table('espacio',
    sa.Column('id_espacio', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('permitido', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('no_permitido', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('max_horas', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo IN ('cancha','sala','plaza','otro')", name='ck_espacio_tipo'),
    sa.CheckConstraint('capacidad > 0', name='ck_espacio_capacidad_positiva'),
    sa.CheckConstraint('max_horas > 0', name='ck_espacio_max_horas_positivo'),
    sa.CheckConstraint('valor >= 0', name='ck_espacio_valor_positivo'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_espacio'),
    schema='vecindapp'
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('pass_hash', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('id_junta', 'email', name='ux_usuario_email'),
    schema='vecindapp'
    )
    op.create_table('directiva',
    sa.Column('id_directiva', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('nombres', sa.Text(), nullable=False),
    sa.Column('apellido_paterno', sa.Text(), nullable=False),
    sa.Column('apellido_materno', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('cargo', sa.Text(), nullable=False),
    sa.Column('fecha_inicio_cargo', sa.Date(), nullable=False),
    sa.Column('fecha_termino_cargo', sa.Date(), nullable=True),
    sa.Column('foto_perfil', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cargo IN ('presidente','vicepresidente','secretario','tesorero','director','vocal')", name='ck_directiva_cargo'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_directiva'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('rut'),
    schema='vecindapp'
    )
    op.create_table('payment_intent',
    sa.Column('id_payment_intent', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mp_preference_id', sa.Text(), nullable=True),
    sa.Column('mp_init_point', sa.Text(), nullable=True),
    sa.Column('mp_sandbox_init_point', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.CheckConstraint("entity_type = ANY (ARRAY['certificado'::text, 'reserva'::text])", name='ck_payment_intent_entity_type'),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'expired'::text, 'cancelled'::text])", name='ck_payment_intent_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_intent_amount_positive'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_payment_intent'),
    schema='vecindapp'
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('id_rol', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['vecindapp.rol.id_rol'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol'),
    schema='vecindapp'
    )
    op.create_table('vecino',
    sa.Column('id_vecino', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=True),
    sa.Column('rut', sa.Text(), nullable=False),
    sa.Column('nombres', sa.Text(), nullable=False),
    sa.Column('apellido_paterno', sa.Text(), nullable=False),
    sa.Column('apellido_materno', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('foto_perfil', sa.LargeBinary(), nullable=True),
    sa.Column('id_comuna', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_comuna'], ['vecindapp.comuna.id_comuna'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_vecino'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('rut'),
    schema='vecindapp'
    )
    op.create_table('certificado_pedido',
    sa.Column('id_pedido', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_vecino', sa.BigInteger(), nullable=False),
    sa.Column('creado_por', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('motivo_solicitud', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('iniciado','pendiente_pago','emitido','rechazado')", name='ck_cert_pedido_estado'),
    sa.ForeignKeyConstraint(['creado_por'], ['vecindapp.usuario.id_usuario'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vecino'], ['vecindapp.vecino.id_vecino'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pedido'),
    schema='vecindapp'
    )
    op.create_index('ix_cert_pedido_estado', 'certificado_pedido', ['id_junta', 'estado'], unique=False, schema='vecindapp')
    op.create_table('payment_transaction',
    sa.Column('id_payment_transaction', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_payment_intent', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payment_method_id', sa.Text(), nullable=True),
    sa.Column('payment_type_id', sa.Text(), nullable=True),
    sa.Column('installments', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('payer_email', sa.Text(), nullable=True),
    sa.Column('payer_identification_type', sa.Text(), nullable=True),
    sa.Column('payer_identification_number', sa.Text(), nullable=True),
    sa.CheckConstraint("provider = ANY (ARRAY['mercadopago'::text, 'stripe'::text, 'webpay'::text])", name='ck_payment_transaction_provider'),
    sa.CheckConstraint("status = ANY (ARRAY['created'::text, 'pending'::text, 'in_process'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text, 'refunded'::text, 'charged_back'::text])", name='ck_payment_transaction_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['id_payment_intent'], ['vecindapp.payment_intent.id_payment_intent'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_payment_transaction'),
    schema='vecindapp'
    )
    op.create_table('reserva',
    sa.Column('id_reserva', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_espacio', sa.BigInteger(), nullable=False),
    sa.Column('id_vecino', sa.BigInteger(), nullable=False),
    sa.Column('creado_por', sa.BigInteger(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('pendiente','pagada','aprobada','rechazada','cancelada','confirmada')", name='ck_reserva_estado'),
    sa.CheckConstraint('fin > inicio', name='ck_reserva_intervalo'),
    sa.ForeignKeyConstraint(['creado_por'], ['vecindapp.usuario.id_usuario'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_espacio'], ['vecindapp.espacio.id_espacio'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vecino'], ['vecindapp.vecino.id_vecino'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reserva'),
    schema='vecindapp'
    )
    op.create_index('ix_reserva_espacio_tiempo', 'reserva', ['id_espacio', 'inicio', 'fin'], unique=False, schema='vecindapp')
    op.create_index('ix_reserva_estado', 'reserva', ['id_junta', 'estado'], unique=False, schema='vecindapp')
    op.create_table('certificado',
    sa.Column('id_certificado', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BigInteger(), nullable=False),
    sa.Column('id_pedido', sa.BigInteger(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('comuna', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pedido'], ['vecindapp.certificado_pedido.id_pedido'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_certificado'),
    sa.UniqueConstraint('id_junta', 'numero', name='ux_cert_num'),
    sa.UniqueConstraint('id_pedido'),
    schema='vecindapp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificado', schema='vecindapp')
    op.drop_index('ix_reserva_estado', table_name='reserva', schema='vecindapp')
    op.drop_index('ix_reserva_espacio_tiempo', table_name='reserva', schema='vecindapp')
    op.drop_table('reserva', schema='vecindapp')
    op.drop_table('payment_transaction', schema='vecindapp')
    op.drop_index('ix_cert_pedido_estado', table_name='certificado_pedido', schema='vecindapp')
    op.drop_table('certificado_pedido', schema='vecindapp')
    op.drop_table('vecino', schema='vecindapp')
    op.drop_table('usuario_rol', schema='vecindapp')
    op.drop_table('payment_intent', schema='vecindapp')
    op.drop_table('directiva', schema='vecindapp')
    op.drop_table('usuario', schema='vecindapp')
    op.drop_table('espacio', schema='vecindapp')
    op.drop_table('junta', schema='vecindapp')
    op.drop_table('comuna', schema='vecindapp')
    op.drop_index('ix_webhook_provider_external_id', table_name='webhook_event', schema='vecindapp')
    op.drop_table('webhook_event', schema='vecindapp')
    op.drop_table('rol', schema='vecindapp')
    op.drop_table('region', schema='vecindapp')
    # ### end Alembic commands ###
