"""agregar_motivo_solicitud_certificado

Revision ID: 6793fd52c084
Revises: 87acd0de0c28
Create Date: 2025-09-21 22:00:12.204864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6793fd52c084'
down_revision: Union[str, Sequence[str], None] = '87acd0de0c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificado_pedido', sa.Column('motivo_solicitud', sa.Text(), nullable=True), schema='vecindapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificado_pedido', 'motivo_solicitud', schema='vecindapp')
    # ### end Alembic commands ###
