"""agregar_campos_junta_rut_fecha_activa_logo

Revision ID: b7e71de52c46
Revises: 1d39f1de7f47
Create Date: 2025-09-23 16:23:48.420227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e71de52c46'
down_revision: Union[str, Sequence[str], None] = '1d39f1de7f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Agregar campos que pueden ser NULL inicialmente
    op.add_column('junta', sa.Column('rut', sa.Text(), nullable=True), schema='vecindapp')
    op.add_column('junta', sa.Column('fecha_constitucion', sa.Date(), nullable=True), schema='vecindapp')
    op.add_column('junta', sa.Column('activa', sa.Boolean(), nullable=False, server_default=sa.text('true')), schema='vecindapp')
    op.add_column('junta', sa.Column('logo', sa.LargeBinary(), nullable=True), schema='vecindapp')
    
    # Actualizar registros existentes con RUT temporal basado en ID
    # Esto permite que los registros existentes tengan un RUT válido
    op.execute("""
        UPDATE vecindapp.junta 
        SET rut = 'TEMP-' || id_junta::text 
        WHERE rut IS NULL
    """)
    
    # Ahora hacer el campo RUT NOT NULL y agregar la constraint única
    op.alter_column('junta', 'rut', nullable=False, schema='vecindapp')
    op.create_unique_constraint('uq_junta_rut', 'junta', ['rut'], schema='vecindapp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_junta_rut', 'junta', schema='vecindapp', type_='unique')
    op.drop_column('junta', 'logo', schema='vecindapp')
    op.drop_column('junta', 'activa', schema='vecindapp')
    op.drop_column('junta', 'fecha_constitucion', schema='vecindapp')
    op.drop_column('junta', 'rut', schema='vecindapp')
    # ### end Alembic commands ###
