"""eliminar_modelos_de_pago

Revision ID: da15403acd2e
Revises: 0290d5aa448b
Create Date: 2025-09-22 18:09:31.066201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da15403acd2e'
down_revision: Union[str, Sequence[str], None] = '0290d5aa448b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Eliminar tablas dependientes primero, luego la tabla principal
    # Eliminar tablas que dependen de transaccion
    op.drop_table('detalle_transaccion', schema='vecindapp')
    op.drop_table('pago_externo', schema='vecindapp')
    # Eliminar índice y tabla principal
    op.drop_index(op.f('ix_tx_origen'), table_name='transaccion', schema='vecindapp')
    op.drop_table('transaccion', schema='vecindapp')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago_externo',
    sa.Column('id_pago_externo', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_transaccion', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('codigo_respuesta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado_pago', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fecha_respuesta', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_transaccion'], ['vecindapp.transaccion.id_transaccion'], name=op.f('pago_externo_id_transaccion_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pago_externo', name=op.f('pago_externo_pkey')),
    sa.UniqueConstraint('id_transaccion', name=op.f('ux_pagoext_tx'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='vecindapp'
    )
    op.create_table('detalle_transaccion',
    sa.Column('id_detalle', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_transaccion', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('etiqueta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_transaccion'], ['vecindapp.transaccion.id_transaccion'], name=op.f('detalle_transaccion_id_transaccion_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle', name=op.f('detalle_transaccion_pkey')),
    schema='vecindapp'
    )
    op.create_table('transaccion',
    sa.Column('id_transaccion', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('id_junta', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('origen_tipo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('origen_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('proveedor', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('monto', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('moneda', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creado_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('autorizado_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('anulado_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("estado = ANY (ARRAY['iniciado'::text, 'autorizado'::text, 'rechazado'::text, 'anulado'::text])", name=op.f('ck_tx_estado')),
    sa.CheckConstraint("origen_tipo = ANY (ARRAY['certificado_pedido'::text, 'reserva'::text])", name=op.f('ck_tx_origen_tipo')),
    sa.CheckConstraint("proveedor = ANY (ARRAY['webpay'::text, 'mercadopago'::text, 'paypal'::text])", name=op.f('ck_tx_proveedor')),
    sa.CheckConstraint('monto >= 0::numeric', name=op.f('ck_tx_monto')),
    sa.ForeignKeyConstraint(['id_junta'], ['vecindapp.junta.id_junta'], name=op.f('transaccion_id_junta_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], name=op.f('transaccion_id_usuario_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_transaccion', name=op.f('transaccion_pkey')),
    schema='vecindapp'
    )
    op.create_index(op.f('ix_tx_origen'), 'transaccion', ['id_junta', 'origen_tipo', 'origen_id'], unique=False, schema='vecindapp')
    # ### end Alembic commands ###
