"""agregar_sistema_pagos_limpio

Revision ID: ddacb33eebe2
Revises: da15403acd2e
Create Date: 2025-09-22 19:18:45.705170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddacb33eebe2'
down_revision: Union[str, Sequence[str], None] = 'da15403acd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_event',
    sa.Column('id_webhook_event', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('processing_attempts', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id_payment_transaction', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("provider = ANY (ARRAY['mercadopago'::text, 'stripe'::text, 'webpay'::text])", name='ck_webhook_event_provider'),
    sa.CheckConstraint("status = ANY (ARRAY['received'::text, 'processing'::text, 'processed'::text, 'failed'::text, 'ignored'::text])", name='ck_webhook_event_status'),
    sa.PrimaryKeyConstraint('id_webhook_event'),
    schema='vecindapp'
    )
    op.create_index('ix_webhook_provider_external_id', 'webhook_event', ['provider', 'external_id'], unique=True, schema='vecindapp')
    op.create_table('payment_intent',
    sa.Column('id_payment_intent', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.BigInteger(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mp_preference_id', sa.Text(), nullable=True),
    sa.Column('mp_init_point', sa.Text(), nullable=True),
    sa.Column('mp_sandbox_init_point', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.CheckConstraint("entity_type = ANY (ARRAY['certificado'::text, 'reserva'::text])", name='ck_payment_intent_entity_type'),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'expired'::text, 'cancelled'::text])", name='ck_payment_intent_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_intent_amount_positive'),
    sa.ForeignKeyConstraint(['id_usuario'], ['vecindapp.usuario.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_payment_intent'),
    schema='vecindapp'
    )
    op.create_table('payment_transaction',
    sa.Column('id_payment_transaction', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_payment_intent', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('external_reference', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('payment_method_id', sa.Text(), nullable=True),
    sa.Column('payment_type_id', sa.Text(), nullable=True),
    sa.Column('installments', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('payer_email', sa.Text(), nullable=True),
    sa.Column('payer_identification_type', sa.Text(), nullable=True),
    sa.Column('payer_identification_number', sa.Text(), nullable=True),
    sa.CheckConstraint("provider = ANY (ARRAY['mercadopago'::text, 'stripe'::text, 'webpay'::text])", name='ck_payment_transaction_provider'),
    sa.CheckConstraint("status = ANY (ARRAY['created'::text, 'pending'::text, 'in_process'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text, 'refunded'::text, 'charged_back'::text])", name='ck_payment_transaction_status'),
    sa.CheckConstraint('amount > 0', name='ck_payment_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['id_payment_intent'], ['vecindapp.payment_intent.id_payment_intent'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_payment_transaction'),
    schema='vecindapp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_transaction', schema='vecindapp')
    op.drop_table('payment_intent', schema='vecindapp')
    op.drop_index('ix_webhook_provider_external_id', table_name='webhook_event', schema='vecindapp')
    op.drop_table('webhook_event', schema='vecindapp')
    # ### end Alembic commands ###
